[phases.setup]
nixPkgs = ["php", "phpPackages.composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php -d extension=pdo_mysql.so artisan serve --host=0.0.0.0 --port=$PORT"
